version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:*"
        versions: ">= 11.0"
  - package-ecosystem: "maven"
    directory: "/jetty-daemon/src/it/jetty"
    schedule:
      interval: "daily"
    ignore:
      # Jetty 9 supports Servlets 4.0.
      - dependency-name: "javax.servlet:javax.servlet-api"
        versions: ">= 4.1.0"
  - package-ecosystem: "maven"
    directory: "/jetty-daemon/src/it/jetty-proxy"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:*"
        versions: ">= 11.0"
  - package-ecosystem: "maven"
    directory: "/jetty-daemon/src/it/jetty-request-log"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/jetty-daemon/src/it/war"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "javax.servlet:javax.servlet-api"
        versions: ">= 4.1.0"
