version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-webapp"
        versions: ">= 10.0"
  - package-ecosystem: "maven"
    directory: "/jetty-daemon/src/it/jetty"
    schedule:
      interval: "daily"
    ignore:
      # Jetty 9 supports Servlets 3.1.
      - dependency-name: "javax.servlet:javax.servlet-api"
        versions: "> 3.1.0"
  - package-ecosystem: "maven"
    directory: "/jetty-daemon/src/it/jetty-proxy"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-proxy"
        versions: ">= 10.0"
  - package-ecosystem: "maven"
    directory: "/jetty-daemon/src/it/jetty-request-log"
    schedule:
      interval: "daily"
