version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.eclipse.jetty:jetty-webapp"
        versions: ">= 10.0"
  - package-ecosystem: "maven"
    directory: "/daemon-maven-plugin/src/it/jetty"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "//daemon-maven-plugin/src/it/jetty-request-log"
    schedule:
      interval: "daily"
